### ISSUE TITLE
ERROR panic: thread 'main' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by mia0x75** [MagmaWM/MagmaWM#74]
CPU ARMv7 Processor rev 4, 4-Core
GPU: Mali G31 ARM
Memory: 2G
eMMC: 8G
OS: Armbian
Kernel: Linux armbian 6.1.82

latest git version:
```
2024-03-22T05:47:37.200134Z  INFO smithay::wayland::output: Creating new wl_output output="HDMI-A-1"
2024-03-22T05:47:37.200368Z  WARN new: smithay::backend::drm::compositor: Preferred format AB30 not available: NoSupportedPlaneFormat
2024-03-22T05:47:37.200426Z  WARN new: smithay::backend::drm::compositor: Preferred format AR30 not available: NoSupportedPlaneFormat
2024-03-22T05:47:37.244397Z  INFO smithay::backend::drm::surface::atomic: Setting new mode: "1280x1024"
2024-03-22T05:47:37.442338Z  WARN smithay::backend::drm::device::fd: Unable to become drm master, assuming unprivileged mode
2024-03-22T05:47:37.442507Z  INFO smithay::backend::drm::device: DrmDevice initializing
2024-03-22T05:47:37.442733Z  INFO smithay::backend::drm::device::fd: Dropping device: Some("/dev/dri/card1")
2024-03-22T05:47:37.499460Z ERROR panic: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Access { errmsg: "Error loading resource handles", dev: Some("/dev/dri/card1"), source: Os { code: 95, kind: Uncategorized, message: "Operation not supported" } }': src/backends/udev.rs:399   0: magmawm::main::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   7: magmawm::backends::udev::<impl magmawm::state::MagmaState<magmawm::backends::udev::UdevData>>::on_device_added
   8: magmawm::backends::udev::<impl magmawm::state::MagmaState<magmawm::backends::udev::UdevData>>::on_udev_event
   9: magmawm::backends::udev::init_udev
  10: magmawm::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: std::rt::lang_start::{{closure}}
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  14: main
  15: <unknown>
  16: __libc_start_main
  17: _start

2024-03-22T05:47:37.918635Z ERROR drm_atomic: smithay::backend::drm::device::atomic: Failed to restore previous state. Error: Permission denied (os error 13)
2024-03-22T05:47:37.918996Z  INFO smithay::backend::drm::device::fd: Dropping device: Some("/dev/dri/card0")
```

**Comment by electron271** [comment]
sorry for taking so long, ill look into this

as far as i know arm hasnt been tested, so im not sure how well magma works on arm

**Comment by electron271** [comment]
are you running magmawm using sudo or just regularly? if regular try with sudo

when debugging a issue also please use `RUST_LOG=debug`, you can find logs at `$HOME/.local/share/MagmaWM/`

sorry for it not being very clear about how to debug it, ill make a pr for that

**Comment by mia0x75** [comment]
Here it is.
[magma_2024-03-31_22:53:24.log](https://github.com/MagmaWM/MagmaWM/files/14816408/magma_2024-03-31_22.53.24.log)

**Comment by HackedOS** [comment]
> Here it is. Run as root user. [magma_2024-03-31_22:53:24.log](https://github.com/MagmaWM/MagmaWM/files/14816408/magma_2024-03-31_22.53.24.log)

sorry for the late reply we found your issue forgot to tell you, it has to do with either your distro or filesystem. can you tell us what your filesystem is. and also run `ls -lah /dev/dri/card0` and give us the output. once again sorry for the delay

**Comment by mia0x75** [comment]
```
# ls -lah /dev/dri/card0
crw-rw---- 1 root video 226, 0 Apr 7 19:31 /dev/dri/card0
```

I saw another 2 issues of niri project fixed several days ago, FYI
https://github.com/YaLTeR/niri/issues/218
https://github.com/YaLTeR/niri/issues/274

And I can run niri 0.14 locally right now.

**Comment by HackedOS** [comment]
Seems like i have skill issue can u try `ls -lah /dev/dri/card1`

**Comment by mia0x75** [comment]
```
# ls -lah /dev/dri/
total 0
drwxr-xr-x  3 root root        100 Apr 13 16:32 .
drwxr-xr-x 16 root root       5.8K Apr 13 16:32 ..
drwxr-xr-x  2 root root         80 Apr 13 16:32 by-path
crw-rw----  1 root video  226,   0 Apr 13 16:32 card0
crw-rw----  1 root render 226, 128 Apr 13 16:32 renderD128
```

**Comment by HackedOS** [comment]
> ```
> # ls -lah /dev/dri/
> total 0
> drwxr-xr-x  3 root root        100 Apr 13 16:32 .
> drwxr-xr-x 16 root root       5.8K Apr 13 16:32 ..
> drwxr-xr-x  2 root root         80 Apr 13 16:32 by-path
> crw-rw----  1 root video  226,   0 Apr 13 16:32 card0
> crw-rw----  1 root render 226, 128 Apr 13 16:32 renderD128
> ```

Ok found ur issue, the comp is trying to ise card1 when it clearly does not exist
